version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "10:00"
    timezone: Europe/Amsterdam
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@babel/core"
    versions:
    - 7.12.17
    - 7.13.1
    - 7.13.10
    - 7.13.13
    - 7.13.14
    - 7.13.15
    - 7.13.16
    - 7.13.8
  - dependency-name: webpack
    versions:
    - 5.23.0
    - 5.24.0
    - 5.24.1
    - 5.24.2
    - 5.24.3
    - 5.25.1
    - 5.27.1
    - 5.28.0
    - 5.30.0
    - 5.31.2
  - dependency-name: eslint
    versions:
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: "@babel/preset-react"
    versions:
    - 7.12.13
    - 7.13.13
  - dependency-name: webpack-cli
    versions:
    - 4.5.0
    - 4.6.0
  - dependency-name: chai
    versions:
    - 4.3.3
    - 4.3.4
  - dependency-name: mocha
    versions:
    - 8.3.1
    - 8.3.2
  - dependency-name: camunda-modeler-plugin-helpers
    versions:
    - 3.4.0-alpha.1
  - dependency-name: eslint-plugin-bpmn-io
    versions:
    - 0.12.0
